// Pure server-side renderers that turn a GeneratedDocument into shareable files.
// PDF via pdf-lib, DOCX via docx — both already in package.json. No "server-only"
// import so these can be unit-tested directly under vitest/node.

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { docTypeLabels, type DocumentRenderMeta, type GeneratedDocument } from "./types";

function metaLine(doc: GeneratedDocument, meta: DocumentRenderMeta): string {
  const parts = [
    docTypeLabels[doc.doc_type],
    meta.company ? `Company: ${meta.company}` : null,
    meta.revision ? `Revision: ${meta.revision}` : null,
    meta.generatedBy ? `Generated by: ${meta.generatedBy}` : null,
  ].filter(Boolean) as string[];
  return parts.join("  ·  ");
}

// ---- PDF ---------------------------------------------------------------------

function wrapText(text: string, font: import("pdf-lib").PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const rawLine of text.split("\n")) {
    const words = rawLine.split(/\s+/).filter(Boolean);
    let line = "";
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = candidate;
      }
    }
    lines.push(line);
  }
  return lines;
}

/** Render the document to a branded, paginated PDF. Returns PDF bytes. */
export async function renderPdf(doc: GeneratedDocument, meta: DocumentRenderMeta = {}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 612; // US Letter
  const pageHeight = 792;
  const margin = 56;
  const maxWidth = pageWidth - margin * 2;
  const gold = rgb(0.788, 0.576, 0.169);
  const ink = rgb(0.12, 0.12, 0.12);
  const muted = rgb(0.45, 0.45, 0.45);

  let page = pdf.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  const ensureSpace = (needed: number) => {
    if (y - needed < margin + 40) {
      page = pdf.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
  };

  const drawLines = (
    text: string,
    opts: { size: number; font: import("pdf-lib").PDFFont; color?: import("pdf-lib").RGB; gap?: number; indent?: number },
  ) => {
    const indent = opts.indent ?? 0;
    const lines = wrapText(text, opts.font, opts.size, maxWidth - indent);
    const lineHeight = opts.size * 1.4;
    for (const line of lines) {
      ensureSpace(lineHeight);
      page.drawText(line, { x: margin + indent, y, size: opts.size, font: opts.font, color: opts.color ?? ink });
      y -= lineHeight;
    }
    y -= opts.gap ?? 0;
  };

  // Header
  drawLines(doc.title, { size: 20, font: bold, color: ink, gap: 4 });
  drawLines(metaLine(doc, meta), { size: 9, font, color: muted, gap: 10 });
  if (doc.summary) drawLines(doc.summary, { size: 11, font, color: ink, gap: 14 });

  // Sections
  for (const section of doc.sections) {
    ensureSpace(28);
    drawLines(section.heading, { size: 13, font: bold, color: gold, gap: 4 });
    if (section.body) drawLines(section.body, { size: 11, font, color: ink, gap: section.items.length ? 4 : 12 });
    for (const item of section.items) {
      drawLines(`•  ${item}`, { size: 11, font, color: ink, gap: 0, indent: 14 });
    }
    if (section.items.length) y -= 12;
  }

  // Disclaimer footer
  ensureSpace(40);
  y -= 8;
  drawLines(doc.disclaimer, { size: 8, font, color: muted, gap: 0 });

  return pdf.save();
}

// ---- DOCX --------------------------------------------------------------------

/** Render the document to an editable Word .docx. Returns DOCX bytes. */
export async function renderDocx(doc: GeneratedDocument, meta: DocumentRenderMeta = {}): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({ text: doc.title, heading: HeadingLevel.TITLE }),
    new Paragraph({ children: [new TextRun({ text: metaLine(doc, meta), color: "777777", size: 18 })] }),
  ];

  if (doc.summary) {
    children.push(new Paragraph({ children: [new TextRun({ text: doc.summary, italics: true })] }));
  }
  children.push(new Paragraph({ text: "" }));

  for (const section of doc.sections) {
    children.push(new Paragraph({ text: section.heading, heading: HeadingLevel.HEADING_2 }));
    if (section.body) children.push(new Paragraph({ text: section.body }));
    for (const item of section.items) {
      children.push(new Paragraph({ text: item, bullet: { level: 0 } }));
    }
  }

  children.push(new Paragraph({ text: "" }));
  children.push(
    new Paragraph({
      alignment: AlignmentType.LEFT,
      children: [new TextRun({ text: doc.disclaimer, italics: true, color: "777777", size: 16 })],
    }),
  );

  const document = new Document({ sections: [{ children }] });
  return Packer.toBuffer(document);
}

/** Filesystem-safe slug for output filenames. */
export function slugifyTitle(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "document"
  );
}
