-- Replace the starter placeholder cars with the actual movable sticker text
-- extracted from brainstorming_parking_lots_draggable.pdf annotations.

with category_seed(slug, title, description, sort_order) as (
  values
    ('brainstorming-parking-lots', 'Brainstorming Parking Lots', 'Movable car stickers for safety platform ideas', 0),
    ('data-management', 'Data Management', 'Recordkeeping, certs, data structure, and multi-location organization', 10),
    ('ai-system-management', 'AI System Management', 'Predictive risk, scoring, alerts, summaries, and trend intelligence', 20),
    ('document-control', 'Document Control', 'Document generation, review workflow, versioning, and client portals', 30),
    ('hse-management-system', 'HSE Management System', 'Inspections, incidents, corrective actions, meetings, permits, and programs', 40),
    ('training-and-certs', 'Training and Certs', 'Training documents, certificate dates, expiration tracking, and compliance reports', 50),
    ('high-risk-and-alerts', 'High Risk and Alerts', 'Serious event alerts, SIFp / IDLH escalation, and cross-location sorting', 60),
    ('inspection-and-forms', 'Inspection and Forms', 'Inspection card variants, custom forms, checklists, and field cards', 70),
    ('integrations', 'Integrations', 'Microsoft, Procore, document storage, calendar, and task connections', 80),
    ('client-setup-options', 'Client Setup Options', 'Account setup choices, module packages, permissions, and onboarding', 90),
    ('pricing-and-model', 'Pricing and Model', 'First-year packages, CSEP reviews, add-ons, tiers, and portal access', 100),
    ('1910-expansion', '1910 Expansion', 'General industry roadmap, written programs, checklists, and future modules', 110),
    ('blank-category-parking-lot', 'Blank Category Parking Lot', 'Use this page to collect future ideas and drag blank cars into the right lane', 120)
)
insert into public.brainstorming_parking_lot_categories (slug, title, description, sort_order)
select slug, title, description, sort_order
from category_seed
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  sort_order = excluded.sort_order;

update public.brainstorming_parking_lot_cards
set
  archived_at = coalesce(archived_at, now()),
  notes = case
    when notes = '' then 'Archived starter placeholder after PDF card import.'
    else notes
  end
where archived_at is null
  and is_placeholder = true;

with seed_cards(slug, lane, sort_order, title, priority) as (
  values
    ('brainstorming-parking-lots', 'do_now', 100, 'Record keeping and certs', 'High'),
    ('brainstorming-parking-lots', 'build_next', 100, 'High risk text alerts', 'Medium'),
    ('brainstorming-parking-lots', 'parking_lot', 100, '1910 expansion roadmap', 'Low'),
    ('data-management', 'do_now', 100, 'Record keeping and certs', 'High'),
    ('data-management', 'do_now', 200, 'Training document uploads', 'High'),
    ('data-management', 'do_now', 300, 'Employee and contractor database', 'High'),
    ('data-management', 'do_now', 400, 'Document expiration tracking', 'High'),
    ('data-management', 'build_next', 100, 'Multi-location data organization', 'Medium'),
    ('data-management', 'build_next', 200, 'Audit trail for uploaded docs', 'Medium'),
    ('data-management', 'build_next', 300, 'Project and jobsite setup', 'Medium'),
    ('data-management', 'build_next', 400, 'User roles and access', 'Medium'),
    ('data-management', 'parking_lot', 100, 'Data migration service', 'Low'),
    ('data-management', 'parking_lot', 200, 'Historical safety data library', 'Low'),
    ('data-management', 'parking_lot', 300, 'Contractor prequalification profile', 'Low'),
    ('data-management', 'parking_lot', 400, 'Dashboard export reports', 'Low'),
    ('ai-system-management', 'do_now', 100, 'High risk dashboard and sorting', 'High'),
    ('ai-system-management', 'do_now', 200, 'Metrics and predictability', 'High'),
    ('ai-system-management', 'do_now', 300, 'AI safety alerts - SIFp / IDLH', 'High'),
    ('ai-system-management', 'do_now', 400, 'AI generated executive summaries', 'High'),
    ('ai-system-management', 'build_next', 100, 'Predictive risk engine', 'Medium'),
    ('ai-system-management', 'build_next', 200, 'Behavior and trend analysis', 'Medium'),
    ('ai-system-management', 'build_next', 300, 'JSA quality scoring', 'Medium'),
    ('ai-system-management', 'build_next', 400, 'Permit completeness scoring', 'Medium'),
    ('ai-system-management', 'parking_lot', 100, 'Leadership rating trends', 'Low'),
    ('ai-system-management', 'parking_lot', 200, 'Monthly risk forecasting', 'Low'),
    ('ai-system-management', 'parking_lot', 300, 'AI system integrity checks', 'Low'),
    ('ai-system-management', 'parking_lot', 400, 'Cross-location risk comparison', 'Low'),
    ('document-control', 'do_now', 100, 'Document generation', 'High'),
    ('document-control', 'do_now', 200, 'CSEP builder', 'High'),
    ('document-control', 'do_now', 300, 'Human review workflow', 'High'),
    ('document-control', 'do_now', 400, 'Version control', 'High'),
    ('document-control', 'build_next', 100, 'PSSP / PSHSEP builder', 'Medium'),
    ('document-control', 'build_next', 200, '1910 program builder', 'Medium'),
    ('document-control', 'build_next', 300, 'Client and subcontractor portal', 'Medium'),
    ('document-control', 'build_next', 400, 'Revision history', 'Medium'),
    ('document-control', 'parking_lot', 100, 'Document scoring', 'Low'),
    ('document-control', 'parking_lot', 200, 'Final PDF / Word export', 'Low'),
    ('document-control', 'parking_lot', 300, 'Annual document maintenance', 'Low'),
    ('document-control', 'parking_lot', 400, 'Custom client library', 'Low'),
    ('hse-management-system', 'do_now', 100, 'Inspections and audits', 'High'),
    ('hse-management-system', 'do_now', 200, 'Corrective actions and follow-up', 'High'),
    ('hse-management-system', 'do_now', 300, 'Incidents and near misses', 'High'),
    ('hse-management-system', 'do_now', 400, 'JSAs / JHAs', 'High'),
    ('hse-management-system', 'build_next', 100, 'Permits', 'Medium'),
    ('hse-management-system', 'build_next', 200, 'Safety meetings and toolbox talks', 'Medium'),
    ('hse-management-system', 'build_next', 300, 'Equipment inspections', 'Medium'),
    ('hse-management-system', 'build_next', 400, 'Emergency action planning', 'Medium'),
    ('hse-management-system', 'parking_lot', 100, 'OSHA 1910 and 1926 modules', 'Low'),
    ('hse-management-system', 'parking_lot', 200, 'HazCom and SDS tracking', 'Low'),
    ('hse-management-system', 'parking_lot', 300, 'Contractor management', 'Low'),
    ('hse-management-system', 'parking_lot', 400, 'Full HSE operating system', 'Low'),
    ('training-and-certs', 'do_now', 100, 'Upload training certificates', 'High'),
    ('training-and-certs', 'do_now', 200, 'Training matrix', 'High'),
    ('training-and-certs', 'do_now', 300, 'Expiration dates and alerts', 'High'),
    ('training-and-certs', 'do_now', 400, 'OSHA card management', 'High'),
    ('training-and-certs', 'build_next', 100, 'Assign certs to employees', 'Medium'),
    ('training-and-certs', 'build_next', 200, 'Skill and competency tracking', 'Medium'),
    ('training-and-certs', 'build_next', 300, 'Compliance reports', 'Medium'),
    ('training-and-certs', 'build_next', 400, 'Employee training history', 'Medium'),
    ('training-and-certs', 'parking_lot', 100, 'Bulk upload and import', 'Low'),
    ('training-and-certs', 'parking_lot', 200, 'Auto reminders', 'Low'),
    ('training-and-certs', 'parking_lot', 300, 'Company-specific training records', 'Low'),
    ('training-and-certs', 'parking_lot', 400, 'Training gap forecast', 'Low'),
    ('high-risk-and-alerts', 'do_now', 100, 'Text alerts for SIFp', 'High'),
    ('high-risk-and-alerts', 'do_now', 200, 'Text alerts for IDLH', 'High'),
    ('high-risk-and-alerts', 'do_now', 300, 'High-risk issue sorting', 'High'),
    ('high-risk-and-alerts', 'do_now', 400, 'Serious event escalation', 'High'),
    ('high-risk-and-alerts', 'build_next', 100, 'Multi-location risk view', 'Medium'),
    ('high-risk-and-alerts', 'build_next', 200, 'Stop-work notifications', 'Medium'),
    ('high-risk-and-alerts', 'build_next', 300, 'Overdue high-risk corrective actions', 'Medium'),
    ('high-risk-and-alerts', 'build_next', 400, 'Emergency escalation workflow', 'Medium'),
    ('high-risk-and-alerts', 'parking_lot', 100, 'Trade-specific alert rules', 'Low'),
    ('high-risk-and-alerts', 'parking_lot', 200, 'Role-based alert routing', 'Low'),
    ('high-risk-and-alerts', 'parking_lot', 300, 'Daily high-risk digest', 'Low'),
    ('high-risk-and-alerts', 'parking_lot', 400, 'Severity threshold settings', 'Low'),
    ('inspection-and-forms', 'do_now', 100, 'Inspection card variants', 'High'),
    ('inspection-and-forms', 'do_now', 200, 'Custom inspection forms', 'High'),
    ('inspection-and-forms', 'do_now', 300, 'Daily and weekly checklists', 'High'),
    ('inspection-and-forms', 'do_now', 400, 'Audit templates', 'High'),
    ('inspection-and-forms', 'build_next', 100, 'Equipment inspections', 'Medium'),
    ('inspection-and-forms', 'build_next', 200, 'Trade-specific cards', 'Medium'),
    ('inspection-and-forms', 'build_next', 300, 'SIFp / IDLH condition card', 'Medium'),
    ('inspection-and-forms', 'build_next', 400, 'Corrective action card', 'Medium'),
    ('inspection-and-forms', 'parking_lot', 100, 'Client setup card choices', 'Low'),
    ('inspection-and-forms', 'parking_lot', 200, 'Permit verification cards', 'Low'),
    ('inspection-and-forms', 'parking_lot', 300, 'Mobile inspection view', 'Low'),
    ('inspection-and-forms', 'parking_lot', 400, 'Form scoring', 'Low'),
    ('integrations', 'do_now', 100, 'MS Scheduler / Project integration', 'High'),
    ('integrations', 'do_now', 200, 'Outlook calendar sync', 'High'),
    ('integrations', 'do_now', 300, 'Teams notifications', 'High'),
    ('integrations', 'do_now', 400, 'SharePoint / OneDrive docs', 'High'),
    ('integrations', 'build_next', 100, 'Procore integration', 'Medium'),
    ('integrations', 'build_next', 200, 'Pull upcoming high-risk work', 'Medium'),
    ('integrations', 'build_next', 300, 'Planner task assignments', 'Medium'),
    ('integrations', 'build_next', 400, 'Project schedule risk forecast', 'Medium'),
    ('integrations', 'parking_lot', 100, 'API integration package', 'Low'),
    ('integrations', 'parking_lot', 200, 'SSO / enterprise login', 'Low'),
    ('integrations', 'parking_lot', 300, 'Client data connectors', 'Low'),
    ('integrations', 'parking_lot', 400, 'Auto safety task creation', 'Low'),
    ('client-setup-options', 'do_now', 100, 'Package and module selection', 'High'),
    ('client-setup-options', 'do_now', 200, 'Inspection card choices', 'High'),
    ('client-setup-options', 'do_now', 300, 'Industry type - 1910 / 1926', 'High'),
    ('client-setup-options', 'do_now', 400, 'User roles and permissions', 'High'),
    ('client-setup-options', 'build_next', 100, 'Custom onboarding workflow', 'Medium'),
    ('client-setup-options', 'build_next', 200, 'Client-specific templates', 'Medium'),
    ('client-setup-options', 'build_next', 300, 'Location setup wizard', 'Medium'),
    ('client-setup-options', 'build_next', 400, 'Subcontractor access settings', 'Medium'),
    ('client-setup-options', 'parking_lot', 100, 'White-label portal', 'Low'),
    ('client-setup-options', 'parking_lot', 200, 'Enterprise multi-location setup', 'Low'),
    ('client-setup-options', 'parking_lot', 300, 'Custom dashboard layout', 'Low'),
    ('client-setup-options', 'parking_lot', 400, 'Client success checklist', 'Low'),
    ('pricing-and-model', 'do_now', 100, 'First-year pricing model', 'High'),
    ('pricing-and-model', 'do_now', 200, 'Subcontractor CSEP review pricing', 'High'),
    ('pricing-and-model', 'do_now', 300, 'Human review fee per CSEP', 'High'),
    ('pricing-and-model', 'do_now', 400, 'Base portal access fee', 'High'),
    ('pricing-and-model', 'build_next', 100, 'Tiered pricing packages', 'Medium'),
    ('pricing-and-model', 'build_next', 200, 'Credit-based document model', 'Medium'),
    ('pricing-and-model', 'build_next', 300, 'Add-on service pricing', 'Medium'),
    ('pricing-and-model', 'build_next', 400, 'Rush review pricing', 'Medium'),
    ('pricing-and-model', 'parking_lot', 100, 'Enterprise pricing model', 'Low'),
    ('pricing-and-model', 'parking_lot', 200, 'Annual maintenance fee', 'Low'),
    ('pricing-and-model', 'parking_lot', 300, 'Training doc migration service', 'Low'),
    ('pricing-and-model', 'parking_lot', 400, 'Integration add-on package', 'Low'),
    ('1910-expansion', 'do_now', 100, '1910 general industry roadmap', 'High'),
    ('1910-expansion', 'do_now', 200, 'Written program requirements', 'High'),
    ('1910-expansion', 'do_now', 300, 'Recordkeeping 1910.1020', 'High'),
    ('1910-expansion', 'do_now', 400, 'Training and competency planning', 'High'),
    ('1910-expansion', 'build_next', 100, 'HazCom / LOTO / PPE modules', 'Medium'),
    ('1910-expansion', 'build_next', 200, 'Compliance checklists', 'Medium'),
    ('1910-expansion', 'build_next', 300, 'Inspection checklists', 'Medium'),
    ('1910-expansion', 'build_next', 400, '1910 document library', 'Medium'),
    ('1910-expansion', 'parking_lot', 100, 'Powered industrial trucks', 'Low'),
    ('1910-expansion', 'parking_lot', 200, 'Machine guarding', 'Low'),
    ('1910-expansion', 'parking_lot', 300, 'Emergency action plans', 'Low'),
    ('1910-expansion', 'parking_lot', 400, 'Hearing and respiratory programs', 'Low'),
    ('blank-category-parking-lot', 'do_now', 100, 'New idea 1', 'High'),
    ('blank-category-parking-lot', 'do_now', 200, 'New idea 2', 'High'),
    ('blank-category-parking-lot', 'do_now', 300, 'New idea 3', 'High'),
    ('blank-category-parking-lot', 'do_now', 400, 'New idea 4', 'High'),
    ('blank-category-parking-lot', 'build_next', 100, 'New idea 5', 'Medium'),
    ('blank-category-parking-lot', 'build_next', 200, 'New idea 6', 'Medium'),
    ('blank-category-parking-lot', 'build_next', 300, 'New idea 7', 'Medium'),
    ('blank-category-parking-lot', 'build_next', 400, 'New idea 8', 'Medium'),
    ('blank-category-parking-lot', 'parking_lot', 100, 'Future idea 1', 'Low'),
    ('blank-category-parking-lot', 'parking_lot', 200, 'Future idea 2', 'Low'),
    ('blank-category-parking-lot', 'parking_lot', 300, 'Future idea 3', 'Low'),
    ('blank-category-parking-lot', 'parking_lot', 400, 'Future idea 4', 'Low')
)
insert into public.brainstorming_parking_lot_cards (
  category_id,
  title,
  description,
  lane,
  sort_order,
  owner,
  priority,
  notes,
  is_placeholder,
  placeholder_slot
)
select
  category.id,
  seed.title,
  '',
  seed.lane,
  seed.sort_order,
  null,
  seed.priority,
  '',
  false,
  null
from seed_cards seed
join public.brainstorming_parking_lot_categories category
  on category.slug = seed.slug
where not exists (
  select 1
  from public.brainstorming_parking_lot_cards existing_card
  where existing_card.category_id = category.id
    and existing_card.archived_at is null
    and lower(existing_card.title) = lower(seed.title)
);
